import sys

tasks = ['hci', 'gap', 'l2cap']

f = open('./inc/task_handlers.h', 'w')
f.write('/* GENERATED BY update.py DO NOT EDIT */\n\n')
f.write('#define TASK_NUM %d\n\n' %(len(tasks)))
f.write('extern task_handler_t task_handlers[];\n\n')
f.write('enum {\n')
for t in tasks:
    f.write('\t%s_TASK_ID,\n' %(t.upper()))
f.write('};\n')

f = open('./src/task_handlers.c', 'w')
f.write('/* GENERATED BY update.py DO NOT EDIT */\n\n')
f.write('#include \"system.h\"\n')
for t in tasks:
    f.write('void %s_task_handler(u8 event_id);\n' %(t))
f.write('\n')
f.write('task_handler_t task_handlers[] = {\n')
for t in tasks:
    f.write('\t%s_task_handler,\n' %(t))
f.write('};\n')
